//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToucheMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public string custId { get; set; }
        public string deliveraddress { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
