//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToucheMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservationInfo
    {
        public int resturantId { get; set; }
        public string Timeslot { get; set; }
        public Nullable<int> TotalNoseats { get; set; }
        public Nullable<int> availableSeats { get; set; }
    
        public virtual restaurant restaurant { get; set; }
    }
}
